name: website-rex-deploy

on:
  push:
    branches:
      - main
    paths:
      - "website/**"
  pull_request:
    paths:
      - "website/**"

jobs:
  rex-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: rex-7567-e27
        uses: mbaraa/rex-action@v1.0
        with:
          server-url: ${{ secrets.REX_SERVER }}
          token: ${{ secrets.REX_KEY }}
          repo-name: dotsync/website
